require("zach.plugins-setup")
require("zach.core.colorscheme")
require("zach.core.options")
require("zach.core.keymaps")
require("zach.plugins.comment")
require("zach.plugins.nvim-tree")
require("zach.plugins.lualine")
require("zach.plugins.telescope")
require("zach.plugins.nvim-cmp")
require("zach.plugins.lsp.mason")
require("zach.plugins.lsp.lspsaga")
require("zach.plugins.lsp.lspconfig")
require("zach.plugins.lsp.null-ls")
require("zach.plugins.autopairs")
-- require("zach.plugins.treesitter")
require("zach.plugins.gitsigns")
